
GET http://localhost:8080/api/teachers/all
Content-Type: application/json

###
POST http://localhost:8080/api/teachers/create
Content-Type: application/json

{
    "first_name": "Henrik",
    "last_name": "Strom",
    "email": "henrik@test.com",
    "password": "12345678",
    "department_id": 1
}

###
GET http://localhost:8080/api/teachers/findOne/8
Content-Type: application/json

###
POST http://localhost:8080/api/teachers/updateOne/8
Content-Type: application/json

{
    "first_name": "Michael",
    "last_name": "Doeh",
    "email": "johny@test.com",
    "password": "12345678",
    "department_id": "1"
}

###
POST http://localhost:8080/api/teachers/delete/8
Content-Type: application/json

