GET http://localhost:8080/api/students/all
Content-Type: application/json

###
POST http://localhost:8080/api/students/create
Content-Type: application/json  


{
    "first_name": "Maya",
    "last_name": "Sørensen",
    "user_name": "Maya1234@kea.dk",
    "password": "12345678",
    "program_id": 2
}




###
GET http://localhost:8080/api/students/findOne/14
Content-Type: application/json

###
POST http://localhost:8080/api/students/update/14
Content-Type: application/json

{
  "first_name": "Maya",
  "last_name": "Soloriya",
  "user_name": "Maya1234@kea.dk",
  "password": "12345678",
  "program_id": 2
}

###
POST http://localhost:8080/api/students/delete/15
Content-Type: application/json


