### Login Teacher
POST http://localhost:8080/api/login/
Content-Type: application/json

{
    "email": "ASBC@kea.dk", 
    "password": "12345678"

}

### Login Student
POST http://localhost:8080/api/login/
Content-Type: application/json

{
    "email": "Maya1234@kea.dk", 
    "password": "12345678"

}

###
GET http://localhost:8080/api/logout/