### Login Teacher
POST http://localhost:8080/api/login/
Content-Type: application/json

{
    "email": "tomp@kea.dk", 
    "password": "12341234"

}

### Login Student
POST http://localhost:8080/api/login/
Content-Type: application/json

{
    "email": "Ole1234@kea.dk", 
    "password": "12341234"

}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "Ole1234@kea.dk", 
    "password": "12341234"

}

###
GET http://localhost:8080/api/logout/